# Generated by Django 2.2.4 on 2019-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
